# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HexoTools.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 0, 491, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choose_blog_position = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.choose_blog_position.setObjectName("choose_blog_position")
        self.horizontalLayout.addWidget(self.choose_blog_position)
        self.open_blog_position = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.open_blog_position.setObjectName("open_blog_position")
        self.horizontalLayout.addWidget(self.open_blog_position)
        self.open_local_debug = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.open_local_debug.setObjectName("open_local_debug")
        self.horizontalLayout.addWidget(self.open_local_debug)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(120, 80, 491, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.close_local_debug = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.close_local_debug.setObjectName("close_local_debug")
        self.horizontalLayout_2.addWidget(self.close_local_debug)
        self.buil_new_draft = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.buil_new_draft.setObjectName("buil_new_draft")
        self.horizontalLayout_2.addWidget(self.buil_new_draft)
        self.buil_new_post = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.buil_new_post.setObjectName("buil_new_post")
        self.horizontalLayout_2.addWidget(self.buil_new_post)
        self.Push_Github = QtWidgets.QPushButton(self.centralwidget)
        self.Push_Github.setGeometry(QtCore.QRect(630, 440, 121, 51))
        self.Push_Github.setObjectName("Push_Github")
        self.Show_message = QtWidgets.QTextBrowser(self.centralwidget)
        self.Show_message.setGeometry(QtCore.QRect(120, 240, 491, 251))
        self.Show_message.setObjectName("Show_message")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(120, 160, 491, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.show_comand = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.show_comand.setObjectName("show_comand")
        self.horizontalLayout_3.addWidget(self.show_comand)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(620, 0, 121, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_gitee = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_gitee.setObjectName("open_gitee")
        self.verticalLayout.addWidget(self.open_gitee)
        self.open_github = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_github.setObjectName("open_github")
        self.verticalLayout.addWidget(self.open_github)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_blog_position.setText(_translate("MainWindow", "选择博客位置"))
        self.open_blog_position.setText(_translate("MainWindow", "打开博客目录"))
        self.open_local_debug.setText(_translate("MainWindow", "打开本地调试"))
        self.close_local_debug.setText(_translate("MainWindow", "关闭本地调试"))
        self.buil_new_draft.setText(_translate("MainWindow", "新建draft文章"))
        self.buil_new_post.setText(_translate("MainWindow", "新建post文章"))
        self.Push_Github.setText(_translate("MainWindow", "Push 到GitHub"))
        self.show_comand.setText(_translate("MainWindow", "常用命令显示"))
        self.open_gitee.setText(_translate("MainWindow", "打开Gitee"))
        self.open_github.setText(_translate("MainWindow", "打开GtHub"))

